# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_field <- function(ci, xi, W, hyper, po, A, dmax, dy, updaten, seed) {
    .Call('_slimy_update_field', PACKAGE = 'slimy', ci, xi, W, hyper, po, A, dmax, dy, updaten, seed)
}

